### ISSUE TITLE
在Spring Boot的启动过程中使用TK的通用Mapper报错

### ISSUE THREAD

**Issue by setamv** [godlike110/tk-mybatis#1]
【环境】：
    Mybatis版本：3.4.2  
    tk版本：mapper-3.3.9
【问题描述】：
    在Spring Boot工程中的一个Service类，定义了一个@PostConstruct初始化方法，里面调用了tk的通用Mapper：SelectByPrimaryKeyMapper，然而，这样会报错，堆栈信息见最后的【错误堆栈】。然而，如果将这部分代码替换成通过非通用Mapper访问（即通过Mybatis的Mapper文件编写SQL），是没有问题的。

    通过代码跟踪，发现问题根源在：org.apache.ibatis.builder.annotation.ProviderSqlSource类中的85行代码处，代码如下：
sql = (String) providerMethod.invoke(providerType.newInstance(), parameterObject);
    上述代码中的providerType的类型为tk.mybatis.mapper.provider.base.BaseSelectProvider，通过tk.mybatis.mapper.common.base.select.SelectByPrimaryKeyMapper类的selectByPrimaryKey方法的注解引入。问题发生在BaseSelectProvider类没有提供无参构造函数，所以导致 providerType.newInstance() 报错“NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()”。

这个不知道是使用tk不正确导致的，还是其他的问题，希望能得到帮助。谢谢！

【错误堆栈】
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseSelectProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:103)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:73)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:134)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 32 common frames omitted
Caused by: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider
	at java.lang.Class.newInstance(Unknown Source)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:85)
	... 43 common frames omitted
Caused by: java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	... 45 common frames omitted

**Comment by godlike110** [comment]
是下载的这个工程打的tk jar包吗  我这边使用是正常的 可能跟你配置有关

**Comment by setamv** [comment]
因为工程的框架是之前搭建好的，具体情况不是很了解，后续我再做个简单的环境看能否复现

**Comment by louie2017** [comment]
楼主有解决吗？我自定义了自己的provider后也有这个问题

**Comment by treezhu** [comment]
MapperScan使用tk.mybatis.spring.annotation这个包下的

**Comment by cfldy** [comment]
@Configuration
public class MybatisConfig {
  /** Mapper扫描配置. 自动扫描将Mapper接口生成代理注入到Spring. */
  @Bean
  public static MapperScannerConfigurer mapperScannerConfigurer() {
    MapperScannerConfigurer mapperScannerConfigurer = new MapperScannerConfigurer();
    mapperScannerConfigurer.setBasePackage("cn.demo.mapper");
    return mapperScannerConfigurer;
  }
MapperScannerConfigurer 使用tk包下的
